coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch: off

ignore:
  - "remoting/remoting-triple/build/generated/source/proto/main/java/triple"  # ignore folders and all its contents